package:
  name: vplants.plantgl
  version: 2.21.1

source:
  path: ..


about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
   - python
   - m4
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - qt ==4.8.6 [osx]
   - qt <5 [linux]
   - boost
   - bison
   - flex 2.5.39
   - cgal
   - gmp
   - ann
   - eigen
   - qhull
   - patchelf [linux]
  run:
   - python
   - openalea.deploy
   - openalea.core
   - qt ==4.8.6 [osx]
   - qt <5 [linux]
   - pyqt
   - gmp
   - mpfr
   - cgal
   - qhull
   - ann
   - boost
   - path.py
