{% set version = "2.24.0" %}

package:
  name: openalea.plantgl
  version: {{ version }}

source:
  path: ..

about:
  home: https://github.com/openalea/plantgl
  license: Cecill-C
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

requirements:
  build:
    - cmake >=3.2.0
    - binutils_impl_linux-64<2.31.0 # [linux]
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libXt-devel') }}           # [linux]
    - {{ cdt('libICE-devel') }}          # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
    - {{ cdt('libSM-devel') }}           # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - python=3.7
    - qt >=5.9.0
    - boost-cpp
    - bison [unix]
    - flex [unix]
    - gmp [unix]
#   - cgal [unix]
    - m2-bison [win]
    - m2-flex [win]
    - qhull
    - eigen
    - ann
    - py-boost
#   - pyqglviewer
    - menuinst [win]
    - setuptools
    - openalea.deploy
    - cmake >=3.12.0
  host:
    - python=3.7
  run:
   - python=3.7
   - qt >=5.9.0
   - boost-cpp
   - gmp [unix]
#  - cgal [unix]
   - qhull
   - ann
   - eigen
   - pyqt >=5.6.0
   - ipython
   - pyopengl
   - py-boost
#  - pyqglviewer
   - scipy
   - matplotlib
   - vs2015_runtime [win and py37]
# test:
#   requires:
#     - nose
#   imports:
#     - openalea.plantgl
#   source_files:
#     - test/test_*.py
#     - test/data
#     - share/
#   commands:
#     - nosetests -v -I test_viewer.py -I test_projpershape.py -I thread.py -I test_geomprinter.py -I test_coneofperception.py -I test_pointgrid.py -I test_depthsortengine.py -I test_zbufferengine.py -I test_shared_data.py -I test_light.py -I test_image.py
