package:
  name: vplants.plantgl
  version: 2.21.1

source:
  path: ..


about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  preserve_egg_dir: True
  number: 0
  script: cp options_conda.py options.py; python setup.py install

requirements:
  build:
   - python
   - m4
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - qt <5
   - boost
   - bison
   - flex 2.5.39
   - cgal
   - gmp
   - ann
   - eigen
   - qhull
   - patchelf [linux]
  run:
   - python
   - openalea.deploy
   - openalea.core
   - qt <5
   - pyqt
   - gmp
   - mpfr
   - cgal
   - qhull
   - ann
   - boost
   - path.py

test:
  requires:
    - nose
  imports:
    - vplants.plantgl
  source_files:
    - test/test_*.py
  commands:
   - nosetests -I test_viewer.py -I test_projpershape.py -I test_geomprinter.py -I thread.py
