{% set version = "3.0.0" %}

package:
  name: openalea.plantgl
  version: {{ version }}

source:
  path: ..

about:
  home: https://github.com/openalea/plantgl
  license: Cecill-C
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  number: 1
  preserve_egg_dir: True

requirements:
  host:
      - python {{PY_VER}}
      - numpy
      - eigen
      - gmp                                # [unix]
      - cgal                               # [unix]
      - qhull
      - ann
      - qt >=5
      - pyqt >=5
      - boost # boost module of conda-forge install boost.python and dependency boost-cpp for the cpp libs.
      - libpng
      - zlib
      - libglu                            # [linux]
      - openalea.deploy
      - setuptools
      - pip
          
  build:
      - binutils_impl_linux-64<2.31.0     # [linux]
      - {{ compiler('cxx') }}
      - bison                             # [unix]
      - flex                              # [unix]
      - m2-bison                          # [win]
      - m2-flex                           # [win]
      - menuinst                          # [win]
      - cmake >=3.12.0
      - pkg-config                         # [linux]
      - make                               # [unix]
      - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
      - {{ cdt('libx11-devel') }}          # [linux]
      - {{ cdt('libxext-devel') }}         # [linux]
      - {{ cdt('libxrender-devel') }}      # [linux]
      - {{ cdt('mesa-libgl-devel') }}      # [linux]
      - {{ cdt('mesa-libegl-devel') }}     # [linux]
      - {{ cdt('mesa-dri-drivers') }}      # [linux]
      - {{ cdt('libxdamage') }}            # [linux]
      - {{ cdt('libxdamage-devel') }}      # [linux]
      - {{ cdt('libxfixes') }}             # [linux]
      - {{ cdt('libxfixes-devel') }}       # [linux]
      - {{ cdt('libxxf86vm') }}            # [linux]
      - {{ cdt('libxxf86vm-devel') }}      # [linux]
      - {{ cdt('libselinux-devel') }}      # [linux]

  run:
      - python {{PY_VER}}
      - {{ pin_compatible('numpy') }}
      - eigen
      - gmp                                # [unix]
      - cgal                               # [unix]
      - qhull
      - ann
      - qt >=5
      - pyqt >=5
      - boost # boost module of conda-forge install boost.python and dependency boost-cpp for the cpp libs.
      - libpng
      - zlib
      - libglu                              # [linux]
      - ipython
      - setuptools
      - pyopengl
   #  - pyqglviewer
   #  - scipy
   #  - matplotlib
   #  - vs2015_runtime [win and py37]

  test:
     requires:
       - pytest
       - matplotlib-base
     imports:
       - openalea.plantgl
       - openalea.plantgl.all
     source_files:
       - test/**
       - share/**
     commands:
       - pytest -v 
