name: Building Package using Conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Setup conda
      run: |
        conda config --add channels conda-forge
        conda config --add channels fredboudon
        conda config --set always_yes yes
        conda config --set remote_read_timeout_secs 600
        conda config --set auto_update_conda False
        conda install conda-build anaconda-client

    - name: Build
      run: |
        conda build . --python=3.8 --numpy=1.16

